server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/users/**
        - id: status-service
          uri: http://status-service.default.svc.cluster.local:8082
          predicates:
            - Path=/status/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
          
          
