name: Build Java JAR

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the build on
  pull_request:
    branches:
      - main  # Adjust to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Create Git Tag
      run: |
        git tag -a v${{ github.run_number }} -m "Release version ${{ github.run_number }}"
        git push origin v${{ github.run_number }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Automated release created by GitHub Actions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.YGITHUB_TOKEN }}

    - name: Upload JAR artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: gateway
        path: target/*.jar  # Assumes Maven output is in the target directory
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: target/gateway-0.0.1-SNAPSHOT.jar  # Path to your JAR file
        asset_name: gateway.jar
        asset_content_type: application/java-archive